# Generated by Django 3.2.24 on 2026-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttrack',
            name='cover_image_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
