# Generated by Django 6.0.6 on 2026-06-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(max_length=500, upload_to='', verbose_name='Фото')),
                ('artist', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('votes', models.IntegerField(default=0, verbose_name='Голоса')),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['-rating'],
            },
        ),
    ]
