# Generated by Django 6.0.6 on 2026-06-23 09:43

import gridfs_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0002_alter_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.FileField(max_length=500, storage=gridfs_storage.storage.GridFSStorage(), upload_to='', verbose_name='Фото'),
        ),
    ]
