# Generated by Django 6.0.6 on 2026-06-29 12:40

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel_app', '0003_alter_card_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('card_id', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'votes',
            },
        ),
    ]
